version: '3.8'
services:
  algs-bot:
    image: ghcr.io/a1uka/tg_enc_apex_bot:latest
    container_name: algs-telegram-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_API_BASE_URL=https://tg-proxy.ejkoplay1.workers.dev/bot${BOT_TOKEN}
      
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true